name: "Build docker image"
description: "Build a docker image"
inputs:
  runner_platorm:
    type: string
    description: "Platform of the github runner for build testing"
    required: false
    default: linux/amd64
  platforms:
    type: string
    description: "Image platform(s)"
    required: true
    default: linux/amd64
  context:
    type: string
    description: "Dockerfile Build context path"
    required: true
  dockerfile:
    type: string
    description: "Dockerfile path"
    required: true
  push:
    type: string
    description: "Push the image to the remote repository. Requires to be pre-authenticated to the registry. Either push or load must be true"
    required: true
    default: 'true'
  build-args:
    type: string
    description: "List of build-time variables"
    required: false
  registry:
    type: string
    description: "Registry to push the image to"
    required: true
  tags:
    type: string
    description: "CSV list of tags to apply to the image"
    required: true
    default: latest
  summary:
    type: boolean
    description: "enable github summary"
    default: true
  pr-comment:
    type: boolean
    description: "enable pr-comment"
    default: true
  trivy-enabled:
    type: boolean
    default: true
  trivy-skip-dirs:
    descriptipn: "skip directories to scan with trivy"
    type: string
  skip-setup-trivy:
    type: boolean
    descriptipn: "skip trivy setup"
    default: false

runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Conditionally format tags with full image + repo definition
      id: process_tags
      env:
        REGISTRY: ${{ inputs.registry }}
        TAGS: ${{ inputs.tags }}
      shell: bash
      run: |
        function process_tags() {
            local processed_tags=()

            # split tag field on comma character and add project + ${{ env.REGISTRY }} + image_name 
            IFS=',' read -ra tags <<< "${{ env.TAGS }}"
            for tag in "${tags[@]}"; do
                case "$tag" in 
                *:*)
                    # tag includes ':' - assume preprocessed and just pass to output
                    processed_tags+=("$tag")
                    ;;
                *)
                    # tag needs to include full host + repo definition
                    processed_tags+=("${{env.REGISTRY }}:$tag")
                    ;;
                esac
            done

            # format full tags into csv for docker/build-push-action
            output_str=$(printf "%s," "${processed_tags[@]}")

            # export first processed tag in list for trivy scan
            echo "first_tag=${processed_tags[0]}" >> $GITHUB_OUTPUT
            echo "processed=$output_str" >> $GITHUB_OUTPUT

            echo "::debug::processed_tags=${processed_tags[@]}"
            echo "::debug::output_str=$output_str"
            echo "::debug::first_tag=${processed_tags[0]}"
        }
        process_tags

    - name: Build container image
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_SUMMARY: false 
      id: docker-build
      with:
        platforms: ${{ inputs.runner_platform }}
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        cache-from: type=registry,ref=${{ inputs.registry }}:buildcache
        cache-to: type=local,dest=cache
        tags: ${{ steps.process_tags.outputs.processed }}
        load: true
        build-args: ${{ inputs.build-args }}
         
    - name: Scan for OIDC credentials
      shell: bash
      run: |
        echo "Scanning for oidc credentials"
        set +e
        docker create --name="tmp_container" ${{ steps.docker-build.outputs.imageid }}
        found=$(docker export tmp_container | tar tf - | grep -e "gha-creds-.*.json" | wc -l)
        if [ $found -ge 1 ]; then
            echo -e "::error::Found oidc credentials\nAdd the following line to your .dockerignore file\ngha-creds-*.json"
        fi
        exit "$found"

    - name: Build and push
      env:
        DOCKER_BUILD_SUMMARY: ${{ inputs.summary }}
      if: ${{ inputs.push }} == true
      uses: docker/build-push-action@v6
      id: docker-build-push
      with:
        platforms: ${{ inputs.platforms }}
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        push: ${{ fromJSON(inputs.push) }}
        tags: ${{ steps.process_tags.outputs.processed }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=local,src=cache
        cache-to: type=registry,ref=${{ inputs.registry }}:buildcache,mode=max
        provenance: ${{ fromJSON(false) }}

    - name: Generate artifact attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ inputs.registry }}
        subject-digest: ${{ steps.docker-build-push.outputs.digest }}
        push-to-registry: true

    - uses: anchore/sbom-action@v0
      id: build-sbom
      with:
        image: ${{ inputs.registry }}@${{ steps.docker-build-push.outputs.digest }}
        output-file: ./sbom.spdx.json
        artifact-name: sbom-${{ join(steps.docker-build-push.outputs.digest, ':') }}.spdx.json
        dependency-snapshot: true
     
    - name: Generate SBOM attestation
      uses: actions/attest-sbom@v1
      with:
        subject-name: ${{ inputs.registry }}
        subject-digest: ${{ steps.docker-build-push.outputs.digest }}
        sbom-path: sbom.spdx.json
        push-to-registry: true 
    
    - name: Run Trivy vulnerability scanner
      uses: celo-org/trivy-composite-action@v1.0.1-alvaro
      if: inputs.trivy-enabled == true
      with:
        image-ref: ${{ steps.process_tags.outputs.first_tag }}
        scan-type: image
        pr-comment: ${{ inputs.pr-comment }}
        summary: ${{ inputs.summary }}
        skip-dirs: ${{ inputs.trivy-skip-dirs }}
        skip-setup: ${{ inputs.skip-setup-trivy }}
