name: "Build and Push Docker Image Using Composite Action"
description: >
  This composite action builds a Docker image from a specified Dockerfile and optionally pushes it to a remote registry.
  It supports multi-platform builds, caching, and includes optional tools like Trivy for vulnerability scanning.

inputs:
  runner-platform:
    type: string
    description: >
      Specifies the platform of the GitHub runner for build testing. Commonly used to test builds on various architectures.
      Default is `linux/amd64`.
    required: false
    default: linux/amd64

  platforms:
    type: string
    description: >
      Comma-separated list of image platforms to target during the build process (e.g., `linux/amd64,linux/arm64`).
    required: true
    default: linux/amd64

  context:
    type: string
    description: >
      The build context path for Docker. Typically, this is the directory where the Dockerfile and associated files are located.
    required: true

  dockerfile:
    type: string
    description: >
      The path to the Dockerfile to use for building the image. This should be relative to the context path.
    required: true

  push:
    type: string
    description: >
      Indicates whether the image should be pushed to the remote registry. Requires prior authentication to the registry.
      Either `push` or `load` must be set to `true`.
    required: true
    default: 'true'

  build-args:
    type: string
    description: >
      A list of build-time variables to pass to the Docker build process. Use a comma-separated format.
    required: false

  registry:
    type: string
    description: >
      The registry to which the image will be pushed (e.g., `docker.io/my-repo` or `ghcr.io/my-org`).
    required: true

  tags:
    type: string
    description: >
      A comma-separated list of tags to apply to the image. For example, `latest,v1.0,v1.0.0`.
    required: true
    default: latest

  summary:
    type: boolean
    description: >
      Enables the generation of a GitHub Action summary for the build process.
    default: true

  pr-comment:
    type: boolean
    description: >
      Enables posting comments on pull requests with details about the build process and results.
    default: true

outputs:
  app-name:
    description: >
      The name of the Docker image without the registry. Useful for identifying the application name.
    value: ${{ steps.process_tags.outputs.base_image_name }}

  full-image-name:
    description: >
      The full name of the Docker image, including the registry. This is useful for pulling or referencing the image.
    value: ${{ steps.process_tags.outputs.first_tag }}
runs:
  using: "composite"
  steps:
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Conditionally format tags with full image + repo definition
      id: process_tags
      env:
        REGISTRY: ${{ inputs.registry }}
        TAGS: ${{ inputs.tags }}
      shell: bash
      run: |
        function process_tags() {
            local processed_tags=()

            # split tag field on comma character and add project + ${{ env.REGISTRY }} + image_name 
            IFS=',' read -ra tags <<< "${{ env.TAGS }}"
            for tag in "${tags[@]}"; do
                case "$tag" in 
                *:*)
                    # tag includes ':' - assume preprocessed and just pass to output
                    processed_tags+=("$tag")
                    ;;
                *)
                    # tag needs to include full host + repo definition
                    processed_tags+=("${{env.REGISTRY }}:$tag")
                    ;;
                esac
            done

            # format full tags into csv for docker/build-push-action
            output_str=$(printf "%s," "${processed_tags[@]}")


            # export first processed tag in list for trivy scan
            echo "base_image_name=$(basename ${{env.REGISTRY}})" >> $GITHUB_OUTPUT
            echo "first_tag=${processed_tags[0]}" >> $GITHUB_OUTPUT
            echo "processed=$output_str" >> $GITHUB_OUTPUT

            echo "::debug::processed_tags=${processed_tags[@]}"
            echo "::debug::output_str=$output_str"
            echo "::debug::first_tag=${processed_tags[0]}"
        }
        process_tags

    - name: Build container image
      uses: docker/build-push-action@v6
      env:
        DOCKER_BUILD_SUMMARY: false 
      id: docker-build
      with:
        platforms: ${{ inputs.runner-platform }}
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        cache-from: type=registry,ref=${{ inputs.registry }}:buildcache
        cache-to: type=local,dest=/tmp/.buildx-cache,mode=max
        tags: ${{ steps.process_tags.outputs.processed }}
        load: true
        build-args: ${{ inputs.build-args }}
         
    - name: Scan for OIDC credentials
      shell: bash
      run: |
        echo "Scanning for oidc credentials"
        set +e
        docker create --name="tmp_container" ${{ steps.docker-build.outputs.imageid }}
        found=$(docker export tmp_container | tar tf - | grep -e "gha-creds-.*.json" | wc -l)
        if [ $found -ge 1 ]; then
            echo -e "::error::Found oidc credentials\nAdd the following line to your .dockerignore file\ngha-creds-*.json"
        fi
        exit "$found"

    - name: Build and push
      env:
        DOCKER_BUILD_SUMMARY: ${{ inputs.summary }}
      if: ${{ inputs.push }} == true
      uses: docker/build-push-action@v6
      id: docker-build-push
      with:
        platforms: ${{ inputs.platforms }}
        file: ${{ inputs.dockerfile }}
        context: ${{ inputs.context }}
        push: ${{ fromJSON(inputs.push) }}
        tags: ${{ steps.process_tags.outputs.processed }}
        build-args: ${{ inputs.build-args }}
        cache-from: type=local,src=/tmp/.buildx-cache
        cache-to: type=registry,ref=${{ inputs.registry }}:buildcache,mode=max
        provenance: ${{ fromJSON(false) }}

    - name: Extract image name from registry for the SBOM attestation artifact name
      id: attestation-artifact-name
      env:
        IMAGE: ${{ steps.process_tags.outputs.first_tag }}
      shell: bash
      run: |
        basename="${IMAGE##*/}"
        stripped_name="${basename%:*}-${basename##*:}"
        echo "name=$stripped_name" >> $GITHUB_OUTPUT

    - name: Generate artifact attestation
      id: attestation
      uses: actions/attest-build-provenance@v2
      with:
        subject-name: ${{ inputs.registry }}
        subject-digest: ${{ steps.docker-build-push.outputs.digest }}
        push-to-registry: true


    - uses: anchore/sbom-action@v0
      id: build-sbom
      with:
        image: ${{ inputs.registry }}@${{ steps.docker-build-push.outputs.digest }}
        output-file: ./sbom.spdx.json
        artifact-name: sbom-${{ steps.attestation-artifact-name.outputs.name }}.spdx.json
        dependency-snapshot: true


    - name: Check SBOM size
      id: sbom-size-check
      shell: bash
      # GitHub Actions predicate files must be <= 16MB; skip attestation if too large
      run: |
        FILE="./sbom.spdx.json"
        MAX=16777216
        FILE_SIZE=$(stat -c%s "$FILE")
        echo "File size: $FILE_SIZE bytes (limit: $MAX bytes)"
        
        if [ $FILE_SIZE -ge $MAX ]; then
          echo "::warning::SBOM file ($FILE_SIZE bytes) exceeds 16MB limit. Skipping attestation upload."
          echo "skip_attestation=true" >> $GITHUB_OUTPUT
        else
          echo "SBOM file size is within limits. Proceeding with attestation."
          echo "skip_attestation=false" >> $GITHUB_OUTPUT
        fi
     
    - name: Generate SBOM attestation
      if: steps.sbom-size-check.outputs.skip_attestation != 'true'
      uses: actions/attest-sbom@v3
      with:
        subject-name: ${{ inputs.registry }}
        subject-digest: ${{ steps.docker-build-push.outputs.digest }}
        sbom-path: sbom.spdx.json
        push-to-registry: true 

    - name: Add commands to summary
      shell: bash
      env:
        REGISTRY: "oci://${{ inputs.registry }}@${{ steps.docker-build-push.outputs.digest }}"
      run: |
        # Write Provenance Verification to Summary
        echo "### Attestation Verification" >> $GITHUB_STEP_SUMMARY
        echo "- Verify Provenance" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        echo "gh attestation verify --repo ${{ github.repository }} --signer-repo celo-org/reusable-workflows $REGISTRY --format json | jq" >> $GITHUB_STEP_SUMMARY
        echo "\`\`\`" >> $GITHUB_STEP_SUMMARY

        # Write SBOM Verification to Summary
        if [ "${{ steps.sbom-size-check.outputs.skip_attestation }}" != "true" ]; then
          echo "- Verify SBOM" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
          echo "gh attestation verify --repo ${{ github.repository }} --signer-repo celo-org/reusable-workflows $REGISTRY --predicate-type https://spdx.dev/Document/v2.3 --format json | jq" >> $GITHUB_STEP_SUMMARY
          echo "\`\`\`" >> $GITHUB_STEP_SUMMARY
        fi
